# -*- coding: utf-8 -*-
"""Video Game Performance Release Year 1970 - 2020

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10sBAg4Kx58bKQ0BvPMAj6HJgKp-rgVN3
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('Video Games Sales (1980-2024) - Raw.csv')
df.info()

# Missing Values Check

df.isnull().sum().sort_values(ascending=False)

# Data Duplication

df.duplicated().sum()

# Outlier Check

## Total Sales Data Check
print(df['total_sales'].describe())

## Total Sales vs Regional Sales Check
total_regional_sales = ['na_sales', 'jp_sales', 'pal_sales', 'other_sales']
df['regional_sales_calculated'] = df[total_regional_sales].sum(axis=1)

df['sales_diff'] = (df['total_sales'] - df['regional_sales_calculated']).abs()

invalid_data = df[df['sales_diff'] >= 0.025]

print(f"Number of Sales Data Anomaly: {len(invalid_data)}")
if len(invalid_data) > 0:
    print("Sample of Sales Data Anomaly:")
    print(invalid_data[['total_sales', 'regional_sales_calculated', 'sales_diff']].head())

## Critic Score
critic_score_anomaly = df[(df['critic_score'] < 0) | (df['critic_score'] > 10)]
print(f"Anomaly: {len(critic_score_anomaly)}")

# Missing Value Handling (Dropped by Release Date Unavailable)

df = df.dropna(subset=['total_sales'])
df = df.dropna(subset=['release_date'])
df = df.reset_index(drop=True)

print(f"Number of Row After NA: {len(df)}")
print(f"Number of NA in total sales: {df['total_sales'].isna().sum()}")
print(f"Number of NA in release_date: {df['release_date'].isna().sum()}")

df.info()

# Missing Value (Replacement)

df['developer'] = df['developer'].fillna('Unknown')
print(f"Jumlah baris kosong di kolom developer: {df['developer'].isna().sum()}")

df.info()

# Date Format

df['release_date'] = pd.to_datetime(df['release_date'])
df['release_year'] = df['release_date'].dt.year
df['release_year'] = df['release_year'].astype('Int64')
print(df[['release_date', 'release_year']].head())

# Release Year Group

df['decade'] = (df['release_year'] // 10) * 10
df['decade_label'] = df['decade'].astype(str) + "s"

bins = [1969, 1989, 1999, 2009, 2019, 2025]
labels = ['80s (Retro)', '90s (Golden Era)', '00s (Modern Transition)', '10s (Modern Era)', '20s (Current)']

df['game_era'] = pd.cut(df['release_year'], bins=bins, labels=labels)

era_counts = df['game_era'].value_counts().sort_index()

df[['release_year', 'decade_label', 'game_era']].head()

# Critic Score Status

df['score_status'] = df['critic_score'].apply(lambda x: 1 if pd.notnull(x) else 0)

# Column Name

df = df.rename(columns={
    'na_sales': 'North America Sales',
    'jp_sales': 'Japan Sales',
    'pal_sales': 'Europe & Africa Sales',
    'other_sales': 'Rest of World Sales'
})

df.info()

# Data Overview

df.describe()
print(df.nunique())

# Sales Distribution By Region

regions = ['North America Sales', 'Japan Sales', 'Europe & Africa Sales', 'Rest of World Sales']
total_region = df[regions].sum().sort_values(ascending=False)

fig, ax = plt.subplots(1, 2, figsize=(16, 7))

sns.barplot(x=total_region.index, y=total_region.values, ax=ax[0], palette='viridis')
ax[0].set_title('Total Sales By Region (Copies in Mio)', fontsize=14)
ax[0].set_xticklabels(['NA', 'JP', 'EU/AF', 'Rest'], rotation=0)

ax[1].pie(total_region, labels=['North America', 'Japan', 'Europe & Africa', 'Rest of World'],
        autopct='%1.1f%%', startangle=140, colors=sns.color_palette('pastel'))
ax[1].set_title('Sales Contribution', fontsize=14)

plt.tight_layout()
plt.show()

# Top Sales By Main Categories

def get_top_sales(df, column, top_n=10):
    return df.groupby(column)['total_sales'].sum().sort_values(ascending=False).head(top_n)

top_consoles = get_top_sales(df, 'console')
top_genres = get_top_sales(df, 'genre')
top_publishers = get_top_sales(df, 'publisher')
top_developers = get_top_sales(df, 'developer')

fig, axes = plt.subplots(2, 2, figsize=(16, 12))
plt.subplots_adjust(hspace=0.4, wspace=0.3)

sns.barplot(x=top_consoles.values, y=top_consoles.index, ax=axes[0,0], palette='viridis')
axes[0,0].set_title('Top 10 Consoles by Total Sales')

sns.barplot(x=top_genres.values, y=top_genres.index, ax=axes[0,1], palette='magma')
axes[0,1].set_title('Top 10 Genres by Total Sales')

sns.barplot(x=top_publishers.values, y=top_publishers.index, ax=axes[1,0], palette='rocket')
axes[1,0].set_title('Top 10 Publishers by Total Sales')

sns.barplot(x=top_developers.values, y=top_developers.index, ax=axes[1,1], palette='mako')
axes[1,1].set_title('Top 10 Developers by Total Sales')

plt.show()

# Top 10 Console & Genre By Region

regions = {
    'North America Sales': 'North America',
    'Japan Sales': 'Japan',
    'Europe & Africa Sales': 'Europe & Africa',
    'Rest of World Sales': 'Rest of World'
}

fig, axes = plt.subplots(2, 2, figsize=(20, 12))
axes = axes.flatten()

for i, (col, title) in enumerate(regions.items()):
    top_10_console = df.groupby('console')[col].sum().sort_values(ascending=False).head(10)
    sns.barplot(x=top_10_console.values, y=top_10_console.index, ax=axes[i], palette='viridis')
    axes[i].set_title(f'Top 10 Consoles in {title}', fontsize=15)
    axes[i].set_xlabel('Sales (Millions)')

plt.tight_layout()
plt.show()

fig, axes = plt.subplots(2, 2, figsize=(20, 12))
axes = axes.flatten()

for i, (col, title) in enumerate(regions.items()):
    top_10_genre = df.groupby('genre')[col].sum().sort_values(ascending=False).head(10)
    sns.barplot(x=top_10_genre.values, y=top_10_genre.index, ax=axes[i], palette='magma')
    axes[i].set_title(f'Top 10 Genres in {title}', fontsize=15)
    axes[i].set_xlabel('Sales (Millions)')

plt.tight_layout()
plt.show()

# Critic Score vs Total Sales Correlation

correlation = df['critic_score'].corr(df['total_sales'])
print(f"Correlation Between Critic Score & Total Sales: {correlation:.2f}")

plt.figure(figsize=(12, 7))

sns.regplot(data=df, x='critic_score', y='total_sales',
            scatter_kws={'alpha':0.3, 'color':'blue'},
            line_kws={'color':'red'})

plt.ylim(0, 20)

plt.title(f'Critic Score vs Total Sales Relation (Correlation: {correlation:.2f})', fontsize=14)
plt.xlabel('Critic Score (0-10)')
plt.ylabel('Total Sales (Millions)')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

# Sales Cluster

from sklearn.cluster import KMeans

X = df[['total_sales']].values

kmeans = KMeans(n_clusters=4, random_state=42)
df['sales_cluster'] = kmeans.fit_predict(X)

print(df.groupby('sales_cluster')['total_sales'].agg(['min', 'max', 'count']))

# Sales Cluster Mapping

mapping = {
    0: 'Bronze',
    3: 'Silver',
    1: 'Gold',
    2: 'Platinum'
}

df['sales_category'] = df['sales_cluster'].map(mapping)

category_order = ['Bronze', 'Silver', 'Gold', 'Platinum']
df['sales_category'] = pd.Categorical(df['sales_category'], categories=category_order, ordered=True)

df.info()

# Critic Score By Sales Cluster

score_check = df.groupby('sales_category', observed=True).agg(
    total_games=('title', 'count'),
    games_with_score=('score_status', 'sum')
).reset_index()

score_check['score_available'] = (score_check['games_with_score'] / score_check['total_games']) * 100

print(score_check)

average_scores = df[df['critic_score'].notna()].groupby('sales_category', observed=True)['critic_score'].mean().reset_index()

average_scores.columns = ['Cluster', 'Average_Critic_Score']
print(average_scores)

plt.figure(figsize=(10, 6))
sns.barplot(data=average_scores, x='Cluster', y='Average_Critic_Score', palette='magma')

plt.title('Average Critic Score By Sales Cluster', fontsize=14)
plt.ylim(0, 10)
plt.ylabel('Average Score')
plt.xlabel('Sales Cluster')

for i, val in enumerate(average_scores['Average_Critic_Score']):
    plt.text(i, val + 0.1, f'{val:.2f}', ha='center', fontweight='bold')

plt.show()

# Top Publisher

platinum_games = df[df['sales_category'] == 'Platinum']

publisher_counts = platinum_games.groupby('publisher')['total_sales'].agg(['count', 'sum']).reset_index()
publisher_counts.columns = ['Publisher', 'Number_of_Game', 'Platinum_Cluster_Sales ']
publisher_counts = publisher_counts.sort_values(by='Number_of_Game', ascending=False)

print("Publisher in Platinum Cluster:")
print(publisher_counts)

plt.figure(figsize=(12, 8))
sns.barplot(data=publisher_counts, x='Number_of_Game', y='Publisher', palette='viridis')

plt.title('Top Publisher', fontsize=15)
plt.xlabel('Number of Game')
plt.ylabel('Publisher')
plt.grid(axis='x', linestyle='--', alpha=0.6)

plt.show()

# Visualization Data Preparation (Wide)

!pip install gspread pandas gspread_dataframe

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
from gspread_dataframe import set_with_dataframe

creds, _ = default()
gc = gspread.authorize(creds)

sh = gc.create('Video Game Sales Dashboard')
worksheet = sh.sheet1

set_with_dataframe(worksheet, df)

print(sh.url)

# Data Frame Pivoting

columns_to_keep = ['title', 'publisher', 'console', 'sales_category', 'critic_score']

sales_columns = ['North America Sales', 'Japan Sales', 'Europe & Africa Sales', 'Rest of World Sales']

df_regional = pd.melt(
    df,
    id_vars=columns_to_keep,
    value_vars=sales_columns,
    var_name='region',
    value_name='sales_amount'
)

print("Data Original (Baris):", len(df))
print("Data Regional (Baris):", len(df_regional))

df_regional.info()

# Visualization Data Preparation (Long)

!pip install gspread gspread_dataframe

import gspread
from google.colab import auth
from google.auth import default
from gspread_dataframe import set_with_dataframe

auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

sh = gc.create('Video Game Sales - Regional Pivot')

worksheet = sh.sheet1
worksheet.update_title('regional_sales_long_format')

set_with_dataframe(worksheet, df_regional)

print(sh.url)